package com.example.rentmg.data.model

import com.google.gson.annotations.SerializedName

/**
 * Property data model representing a real estate property
 * Maps to the Property table in the backend database
 *
 * @property id Unique identifier for the property (generated by backend)
 * @property name Display name of the property
 * @property address Physical address of the property location
 * @property landlordId ID of the user who owns this property
 * @property createdAt Timestamp when property was created
 * @property updatedAt Timestamp when property was last updated
 */
data class Property(
    // Unique ID for the property from backend
    @SerializedName("id")
    val id: Int,

    // Name of the property (e.g., "Sunset Apartments", "Green Valley Complex")
    @SerializedName("name")
    val name: String,

    // Full address of the property
    @SerializedName("address")
    val address: String,

    // ID of the landlord who owns this property
    @SerializedName("landlord_id")
    val landlordId: Int,

    // Timestamp when property was created (ISO 8601 format from backend)
    @SerializedName("created_at")
    val createdAt: String,

    // Timestamp when property was last updated
    @SerializedName("updated_at")
    val updatedAt: String
)

/**
 * Request model for creating a new property
 * Used when landlord adds a new property to their portfolio
 *
 * @property name Name of the property
 * @property address Address of the property
 */
data class PropertyCreateRequest(
    // Name of the new property
    @SerializedName("name")
    val name: String,

    // Address of the new property
    @SerializedName("address")
    val address: String
)